### ISSUE TITLE
Module Doesn't Load

### ISSUE THREAD

**Issue by crossfireprod** [gberg927/MMM-DisneyWaitTimes#1]
The module doesn't load, even when using the demo config in the README.  Potentially relevant Chromium Dev Console output included below, looks like there's a typo somewhere making the module's file path invalid:

![screenshot from 2018-10-08 23-35-01](https://user-images.githubusercontent.com/2859289/46645546-5266e800-cb53-11e8-88c4-b6b4730424a0.png)

**Comment by crossfireprod** [comment]
Confirmed file path issue.  Script and directory name must be identical, and match the module's name.  Module now loads and header text is displayed, but no data.

**Comment by gberg927** [comment]
Thanks for discovering the first issue. Are you getting any errors in either console when nothing displays on the screen? How did you set up MagicMirror? It seems to work for me via docker and serveronly installations.

**Comment by crossfireprod** [comment]
Once the directory / script name issue is fixed, the module loads without any console errors.  When using the example configuration, the "Magic Kingdom" header text is displayed, but nothing else.

Environment is a raspberry pi setup using the "Automatic Installation" option a few days ago.  (Had to rebuild an existing setup due to a failed SD card, and decided to give this module a try in addition to my my existing configuration when I started over.)  As such, a few other modules were installed and are working as expected.

Hope this helps, let me know what additional information might be helpful!

**Comment by gberg927** [comment]
Could you try setting the logRide attribute to true and see if the ride information is outputted to the console. This should be the server console (not chrome).

**Comment by crossfireprod** [comment]
Some very peculiar behavior to report:
- MagicMirror is setup with pm2, as per the standard directions.
- Poked at pm2 with `pm2 logs mm` and did not see anything of interest.
- Moved onto stopping the pm2 instance, and starting "manually" with the shell script pm2 uses in hopes that something interesting would be printed to the console; low and behold - it starts working!

I'd poke around further to try and work out what's different, but I'm out of time this evening.  Let me know what further information I can provide!

**Comment by gberg927** [comment]
Added electron-rebuild to package.json and updated readme.
