### ISSUE TITLE
small error application

### ISSUE THREAD

**Issue by tchouky85** [gberg927/MMM-DisneyWaitTimes#12]
hi,

since the park open again in france.

since the park reopened, I have noticed that I must restart the mirror so that it loads the waiting times on the application, otherwise the display remains closed day after day. No refresh. an idea?
thank you

**Comment by gberg927** [comment]
Hi,

Can you confirm? When you restart the mirror, you see wait time normally, but the next day, the park continues to show closed?

**Comment by tchouky85** [comment]
hi,
yes I confirm when I restart the mirror I have the waiting times displayed during the day. When the park closes, it shows closed.
But the next day and the other days if I do not restart the mirror, it remains closed. no more refreshment.
thanks

**Comment by tchouky85** [comment]
hi, do you have idea for the problem? maybe its not the programm but the source 
the appli magipark on my phone as the same problem

**Comment by gberg927** [comment]
Hi, sorry for the delay in response. There was some issues with the wait time provider. They upgrade their api so everything should be working now.

Please grab the latest code and npm install.

```
cd ~MagicMirror/modules/MMM-DisneyWaitTimes
npm install
npm run rebuild
```

Could you please let me know if this newest version fixed your issue?

**Comment by tchouky85** [comment]
hi ok i look tomorrow and i tell you ^^ thanks

**Comment by tchouky85** [comment]
hi,

i haven't watched every day but it seems to work

**Comment by tchouky85** [comment]
I reinstalled the app completely and nothing works, I just have the name of the park and close

**Comment by gberg927** [comment]
Try pulling the latest version of MMM-DisneyWaitTimes.
