### ISSUE TITLE
Disneyland and DCA not working

### ISSUE THREAD

**Issue by DavidD303** [gberg927/MMM-DisneyWaitTimes#18]
I cant get Disneyland and DCA working is always shows the parks as closed and doesnt list any of the rides.  I have all 4 parks for walt disney world working properly. I tried changing the park names to match the names with themeparks API still not working. Below is my current Disneyland config

              {
                        module: "MMM-DisneyWaitTimes",
                        header: "Magic Kingdom - Disneyland Resort",
                        position: "top_right",
                        config: {
                        park: {
                                name: "Magic Kingdom - Disneyland Resort",
                                rides: [
                                "Gadget's Go Coaster",
                                "Haunted Mansion",
                                "Snow White's Scary Adventures",
                                "Alice in Wonderland",
                                "Astro Orbitor",
                                "Autopia",
                                "Big Thunder Mountain Railroad",
                                "Buzz Lightyear Astro Blasters",
                                "Casey Jr. Circus Train",
                                "Great Moments with Mr. Lincoln",
                                "Dumbo the Flying Elephant",
                                "Finding Nemo",
                                "Indiana Jones Adventure",
                                "\"it's a small world\"",
                                "Jungle Cruise",
                                "Mad Tea Party",
                                "The Many Adventures of Winnie the Pooh",
                                "Matterhorn Bobsleds",
                                "Mickey's House and Meet Mickey",
                                "Millennium Falcon: Smugglers Run",
                                "Mr. Toad's Wild Ride",
                               "Peter Pan's Flight",
                                "Pinocchio's Daring Journey",
                                "Pirates of the Caribbean",
                                "Rodger Rabbit's Car Toon Spin",
                                "Space Mountain",
                                "Star Tours",
                                "Star Wars: Rise of the Resistance",
                                ],
                                logRide: false,
                        },

**Comment by gberg927** [comment]
Added both Disneyland Resort's parks to the module. Your config for Magic Kingdom looks good. Here is what I tested California Adventure with.

{
      module: "MMM-DisneyWaitTimes",
      header: "California Adventure - Disneyland Resort",
      position: "top_left",
      config: {
        park: {
          name: "California Adventure - Disneyland Resort",
          rides: [
            "Silly Symphony Swings",
            "The Little Mermaid ~ Ariel's Undersea Adventure",
            "Goofy's Sky School",
            "Radiator Springs Racers",
            "Mater's Junkyard Jamboree",
            "Carthay Circle Lounge - Alfresco Dining",
            "Frozen – Live at the Hyperion",
            "Luigi's Rollickin' Roadsters",
            "Disney Junior Dance Party!",
            "Pixar Pal-A-Round – Non-Swinging",
            "Lamplight Lounge",
            "Heroic Encounter: Captain Marvel",
            "Inside Out Emotional Whirlwind",
            "Mickey's PhilharMagic",
            "Incredicoaster",
            "Grizzly River Run",
            "Jumpin' Jellyfish",
            "Jessie's Critter Carousel",
            "Pixar Pal-A-Round – Swinging",
            "Monsters, Inc. Mike & Sulley to the Rescue!",
            "Soarin' Around the World",
            "Sorcerer's Workshop - Temporarily Unavailable",
            "Guardians of the Galaxy – Mission: BREAKOUT!",
            "Toy Story Midway Mania!",
            "Turtle Talk with Crush",
            "World of Color",
          ],
          logRide: false
        }
      }
    },

**Comment by gberg927** [comment]
Let me know if they both work for you!

**Comment by DavidD303** [comment]
Thank this worked
