### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by DavidD303** [gberg927/MMM-DisneyWaitTimes#25]
Is there a way to have this also log all the information on to a database running on the same network?

I would like to be able to gather the wait times every ~15 minutes and have it entered in to a database on a server on the same network.

**Comment by gberg927** [comment]
This plugin uses the following library to get the waittimes. You could write something to use that to log.

HOWEVER, I am actually working on that myself for https://themeparkstats.com/
Front end: https://github.com/gberg927/disney-metadata-frontend
Back end: https://github.com/gberg927/disney-metadata-backend

Currently the backend is a graphql endpoint only for the data, but plan on adding a rest API to access the data. I can prioritize that for you. Feel free to add an issue on the backend repo for this.
