### ISSUE TITLE
DL and DCA times not loading

### ISSUE THREAD

**Issue by kmallingham** [gberg927/MMM-DisneyWaitTimes#29]
Hey there,

Im running into issues with data being fetched onto my magic mirror for this module. I double checked the config file and everything looks great, and I made sure to “npm install themeparks - - save”, but nothing is still showing up.

do I need to be in the MagicMirror directory to install themeparks? 
![532D38BC-F5CE-4E49-9719-2F52BA912C56](https://user-images.githubusercontent.com/109449914/182949640-20cc4800-f4c9-4c8c-88e0-7c9fcff92d31.jpeg)

**Comment by kmallingham** [comment]
Here's my config file just in case

{
                    module: "MMM-DisneyWaitTimes",
                    header: "Magic Kingdom - Disneyland Resort",
                    position: "top_right",
                    config: {
                    park: {
                            name: "Magic Kingdom - Disneyland Resort",
                            rides: [
                            "Gadget's Go Coaster",
                            "Haunted Mansion",
                            "Snow White's Scary Adventures",
                            "Alice in Wonderland",
                            "Astro Orbitor",
                            "Autopia",
                            "Big Thunder Mountain Railroad",
                            "Buzz Lightyear Astro Blasters",
                            "Casey Jr. Circus Train",
                            "Great Moments with Mr. Lincoln",
                            "Dumbo the Flying Elephant",
                            "Finding Nemo",
                            "Indiana Jones Adventure",
                            "\"it's a small world\"",
                            "Jungle Cruise",
                            "Mad Tea Party",
                            "The Many Adventures of Winnie the Pooh",
                            "Matterhorn Bobsleds",
                            "Mickey's House and Meet Mickey",
                            "Millennium Falcon: Smugglers Run",
                            "Mr. Toad's Wild Ride",
                           "Peter Pan's Flight",
                            "Pinocchio's Daring Journey",
                            "Pirates of the Caribbean",
                            "Rodger Rabbit's Car Toon Spin",
                            "Space Mountain",
                            "Star Tours",
                            "Star Wars: Rise of the Resistance",
                            ],
                            logRide: false,
                    }
                    }
                    },
{
module: "MMM-DisneyWaitTimes",
header: "California Adventure - Disneyland Resort",
position: "top_right",
config: {
park: {
name: "California Adventure - Disneyland Resort",
rides: [
"Silly Symphony Swings",
"The Little Mermaid ~ Ariel's Undersea Adventure",
"Goofy's Sky School",
"Radiator Springs Racers",
"Mater's Junkyard Jamboree",
"Carthay Circle Lounge - Alfresco Dining",
"Frozen – Live at the Hyperion",
"Luigi's Rollickin' Roadsters",
"Disney Junior Dance Party!",
"Pixar Pal-A-Round – Non-Swinging",
"Lamplight Lounge",
"Heroic Encounter: Captain Marvel",
"Inside Out Emotional Whirlwind",
"Mickey's PhilharMagic",
"Incredicoaster",
"Grizzly River Run",
"Jumpin' Jellyfish",
"Jessie's Critter Carousel",
"Pixar Pal-A-Round – Swinging",
"Monsters, Inc. Mike & Sulley to the Rescue!",
"Soarin' Around the World",
"Sorcerer's Workshop - Temporarily Unavailable",
"Guardians of the Galaxy – Mission: BREAKOUT!",
"Toy Story Midway Mania!",
"Turtle Talk with Crush",
"World of Color",
],
logRide: false
}
}
},

**Comment by gberg927** [comment]
Thanks for the info, i'll test it out and see what's wrong

**Comment by gberg927** [comment]
Remove "Resort" from the park.name value. You can leave "Resort" in the module.name if you want the title in the module to include it.

```
{
      module: "MMM-DisneyWaitTimes",
      header: "Magic Kingdom - Disneyland Resort",
      position: "top_right",
      config: {
        park: {
          name: "Magic Kingdom - Disneyland",
          rides: [
            "Gadget's Go Coaster",
            "Haunted Mansion",
            "Snow White's Scary Adventures",
            "Alice in Wonderland",
            "Astro Orbitor",
            "Autopia",
            "Big Thunder Mountain Railroad",
            "Buzz Lightyear Astro Blasters",
            "Casey Jr. Circus Train",
            "Great Moments with Mr. Lincoln",
            "Dumbo the Flying Elephant",
            "Finding Nemo",
            "Indiana Jones Adventure",
            "it's a small world",
            "Jungle Cruise",
            "Mad Tea Party",
            "The Many Adventures of Winnie the Pooh",
            "Matterhorn Bobsleds",
            "Mickey's House and Meet Mickey",
            "Millennium Falcon: Smugglers Run",
            "Mr. Toad's Wild Ride",
            "Peter Pan's Flight",
            "Pinocchio's Daring Journey",
            "Pirates of the Caribbean",
            "Rodger Rabbit's Car Toon Spin",
            "Space Mountain",
            "Star Tours",
            "Star Wars: Rise of the Resistance",
          ],
          logRide: false,
        }
      }
    },
    {
      module: "MMM-DisneyWaitTimes",
      header: "California Adventure - Disneyland Resort",
      position: "top_right",
      config: {
        park: {
          name: "California Adventure - Disneyland",
          rides: [
            "Silly Symphony Swings",
            "The Little Mermaid ~ Ariel's Undersea Adventure",
            "Goofy's Sky School",
            "Radiator Springs Racers",
            "Mater's Junkyard Jamboree",
            "Carthay Circle Lounge - Alfresco Dining",
            "Frozen – Live at the Hyperion",
            "Luigi's Rollickin' Roadsters",
            "Disney Junior Dance Party!",
            "Pixar Pal-A-Round – Non-Swinging",
            "Lamplight Lounge",
            "Heroic Encounter: Captain Marvel",
            "Inside Out Emotional Whirlwind",
            "Mickey's PhilharMagic",
            "Incredicoaster",
            "Grizzly River Run",
            "Jumpin' Jellyfish",
            "Jessie's Critter Carousel",
            "Pixar Pal-A-Round – Swinging",
            "Monsters, Inc. Mike & Sulley to the Rescue!",
            "Soarin' Around the World",
            "Sorcerer's Workshop - Temporarily Unavailable",
            "Guardians of the Galaxy – Mission: BREAKOUT!",
            "Toy Story Midway Mania!",
            "Turtle Talk with Crush",
            "World of Color",
          ],
          logRide: false
        }
      }
    },
```

**Comment by kmallingham** [comment]
This now works, thanks!!
