### ISSUE TITLE
times do not seem to be updating

### ISSUE THREAD

**Issue by davismorehead** [gberg927/MMM-DisneyWaitTimes#30]
The wait times do not seem to be updating throughout the day. Changed modules/MMM-DisneyWaitTimes/MMM-DisneyWaitTimes.js changed updateInterval from 10 * 60 * 1000 to be 60. Started MM with npm start dev. See 
[03.09.2022 15:03.09.792] [LOG]   Magic Kingdom - Walt Disney World: Processing Wait Times...
[03.09.2022 15:03.09.910] [LOG]   Magic Kingdom - Walt Disney World: Processing Opening Times...
03.09.2022 15:03.10.708] [LOG]   Magic Kingdom - Walt Disney World: Processed Opening Times...
[03.09.2022 15:03.10.732] [LOG]   Magic Kingdom - Walt Disney World: Processed Wait Times...

but never see anything from disney again.

**Comment by davismorehead** [comment]
using the debugger I get the following error every time setInterval goes off

TypeError: this.processWaitTimes is not a function[Learn More]. MMM-DisneyWaitTimes.js:39:7

**Comment by gberg927** [comment]
Can you share the code you changed for updateInterval? 60 millisecond is way too often. It's also possible changing the code caused errors, because processWaitTimes should be present in the file.

**Comment by davismorehead** [comment]
Sure. Just have to figure out how to upload a file. New to git. I did change the timer back to 60 * 1000 or every minute. Was doing that to see setInerval fire off more often. The processWaitTimes outside the setInterval works and they look the same.

**Comment by gberg927** [comment]
Oh okay sounds good. You can just copy and paste the whole file into a comment and put it in a code break (surrounding it with ``)

`Example`

**Comment by davismorehead** [comment]
```
Module.register("MMM-DisneyWaitTimes", {
  defaults: {
    updateInterval: 10 * 60 * 1000 // every 10 minute
  },

  getScripts: function () {
    return ["moment.js"];
  },

  getStyles: function () {
    return ["disney.css"];
  },

  getHeader: function () {
    var headerDiv = document.createElement("div");
    headerDiv.innerHTML = this.data.header;

    var timeSpan = document.createElement("span");
    timeSpan.className = "parkTime";

    if (this.openingTime != null && this.closingTime != null) {
      timeSpan.innerHTML = " " + this.openingTime + " - " + this.closingTime;
    }

    headerDiv.appendChild(timeSpan);

    return headerDiv.innerHTML;
  },

  start: function () {
    Log.info("Starting module: " + this.name);

    this.rides = [];
    this.openingTime;
    this.closingTime;
    this.errorMessage;

    setInterval(function () {
      this.processWaitTimes();
    }, this.config.updateInterval);
    this.processWaitTimes();
  },

  getDom: function () {
    var table = document.createElement("table");
    table.className = "small";
    if (this.errorMessage) {
      var row = document.createElement("tr");
      row.className += "row";
      table.appendChild(row);

      var nameCell = document.createElement("td");
      nameCell.className = "error";
      nameCell.innerHTML = this.errorMessage;
      row.appendChild(nameCell);
    } else {
      for (var i = 0, ride; (ride = this.rides[i++]); ) {
        var row = document.createElement("tr");
        row.className += "row";
        table.appendChild(row);

        var nameCell = document.createElement("td");
        nameCell.className = "bright title";
        nameCell.innerHTML = ride.name;
        row.appendChild(nameCell);

        var timeCell = document.createElement("td");
        timeCell.className = "bright title light time";

        if (ride.status == "Closed") {
          timeCell.innerHTML = "closed";
        } else if (ride.status == "Down") {
          timeCell.innerHTML = "down";
        } else if (ride.status == "Refurbishment") {
          timeCell.innerHTML = "refurb";
        } else {
          timeCell.innerHTML = ride.waitTime;
        }

        row.appendChild(timeCell);
      }
    }
    return table;
  },

  socketNotificationReceived: function (notification, payload) {
    console.log("n: " + notification)
    if (notification === "POPULATE_WAIT_TIMES_" + this.config.park.name) {
      this.rides = payload.waitTimes;
      this.updateDom();
    } else if (
      notification ===
      "POPULATE_OPENING_TIMES_" + this.config.park.name
    ) {
      this.openingTime = payload.openingTime;
      this.closingTime = payload.closingTime;
      this.updateDom();
    } else if (notification === "ERROR_" + this.config.park.name) {
      this.errorMessage = payload.errorMessage;
      this.updateDom();
    }
  },

  processWaitTimes: function () {
    this.sendSocketNotification("GET_WAIT_TIMES", this.config.park);
  }
});
```

**Comment by davismorehead** [comment]
Ok hope that works.

**Comment by gberg927** [comment]
Hmm, I just tried that and it works fine for me. Are you still getting `is not a function` error?

**Comment by davismorehead** [comment]
I'll check.

**Comment by davismorehead** [comment]
Yes still getting error. strange that the first call works, but the updates do not work.

**Comment by gberg927** [comment]
Does the error only happen on the second and following attempts?

**Comment by davismorehead** [comment]
yes. works fine on the first call that is outside the setInterval call.

**Comment by davismorehead** [comment]
also know setInterval is working because I see the Error every ten minutes.

**Comment by gberg927** [comment]
Good catch, I was finally able to reproduce. I fixed the issues in #31. Can you grab latest and try again?

**Comment by davismorehead** [comment]
Will do. Thanks

**Comment by davismorehead** [comment]
That works. Thanks for the quick turnaround. I didn't understand this before. now I really don't understand.
