### ISSUE TITLE
Missing rides at Disney land

### ISSUE THREAD

**Issue by davismorehead** [gberg927/MMM-DisneyWaitTimes#35]
Looks like two rides are missing from Disneyland Magic kingdom. 
I updated parks.json and config.js to add them. Here is the two lines I added to parks.json
      {
        "id": "cd670bff-81d1-4f34-8676-7bafdf49220a",
        "name": "Mickey & Minnie's Runaway Railway"
      },
      {
        "id": "DisneylandResortMagicKingdom_19193461",
        "name": "Star Wars: Rise of the Resistance"
      },
.
Also added to MagicKindom.js

**Comment by davismorehead** [comment]
I have the files, but don't know how to work with github to upload.

**Comment by davismorehead** [comment]
Sorry and my local files are working.

**Comment by gberg927** [comment]
Thanks for catching that. I updated all the parks for new rides.
