### ISSUE TITLE
Screenshot of module in readme

### ISSUE THREAD

**Issue by andyklimczak** [gberg927/MMM-DisneyWaitTimes#4]
Just wondering if a screenshot of the module in use could be added to the readme ([suggested in the MM 3rd party links](https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules#general-advice)). I don't have a MM myself (yet) so I can't do it, but this module in particular caught my interest.

Module seems great, I love the idea. Thanks so much!

**Comment by gberg927** [comment]
Put a screen shot in the readme for you. Enjoy!

**Comment by andyklimczak** [comment]
@gberg927 very much appreciate it! looks awesome
